
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class main extends javax.swing.JFrame {

    String expReg = REGEX;
    String cad = INPUT;
    //expresion regular -> delimita con \b y busca la palabra 'cat'
    private static final String REGEX = "\\bcat\\b";
    //cadena de texto de entrada
    private static final String INPUT = "INGRESE AQUI SU EJEMSPLO";

    public main() {
        initComponents();

        jLabel_regex.setText("Expresion actual: " + expReg);
        jTextField_cadena.setText(cad);

        jComboBox_ejemplos.removeAllItems();
        
        jComboBox_ejemplos.addItem("validar color hexadecimal");
        jComboBox_ejemplos.addItem("validar direccion email");
        jComboBox_ejemplos.addItem("validar miles");
        
        jComboBox_ejemplos.addItem("validar video de youtube");
        jComboBox_ejemplos.addItem("validar ISBN");
        jComboBox_ejemplos.addItem("validar usuario de twitter");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_regex = new javax.swing.JLabel();
        jTextField_cadena = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton_comprobar = new javax.swing.JButton();
        jTextField_regex = new javax.swing.JTextField();
        jButton_cambiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_ejemplos = new javax.swing.JComboBox<>();
        jLabel_res = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("21130876");
        setName("21130876"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("EXPRESIONES REGULARES TAREA 3");

        jLabel_regex.setText("Expresion actual:");

        jTextField_cadena.setToolTipText("");
        jTextField_cadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cadenaActionPerformed(evt);
            }
        });

        jLabel3.setText("Cadena:");

        jButton_comprobar.setText("comprobar");
        jButton_comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_comprobarActionPerformed(evt);
            }
        });

        jTextField_regex.setToolTipText("");
        jTextField_regex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_regexActionPerformed(evt);
            }
        });

        jButton_cambiar.setText("cambiar");
        jButton_cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cambiarActionPerformed(evt);
            }
        });

        jLabel2.setText("Expresion regular:");

        jLabel4.setText("EJEMPLO:");

        jComboBox_ejemplos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_ejemplos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ejemplosItemStateChanged(evt);
            }
        });

        jLabel_res.setText("-----");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_cadena))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_regex))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel_regex)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_ejemplos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_cambiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_comprobar, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabel_res)))
                        .addGap(0, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel_regex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_regex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton_cambiar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_cadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_comprobar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_res)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_ejemplos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_cadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cadenaActionPerformed

    private void jButton_comprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_comprobarActionPerformed
        // TODO add your handling code here:
        //LUIS BARRANCO 21130876
        StringBuilder res = new StringBuilder(" ");

        cad = jTextField_cadena.getText();

        Pattern p = Pattern.compile(expReg); // expresion regular asignada
        Matcher m = p.matcher(cad);   // get a matcher object

        if (m.find()) {
            res.append("COINCIDE!!\n");

            jLabel_res.setText(res.toString());
        } else {
            res.append("NO COINCIDE!!\n");

            jLabel_res.setText(res.toString());
        }
    }//GEN-LAST:event_jButton_comprobarActionPerformed

    private void jTextField_regexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_regexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_regexActionPerformed

    private void jButton_cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cambiarActionPerformed
        // TODO add your handling code here:
        expReg = jTextField_regex.getText();
        jLabel_regex.setText("Expresion actual: " + expReg);
    }//GEN-LAST:event_jButton_cambiarActionPerformed

    private void jComboBox_ejemplosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ejemplosItemStateChanged
        // TODO add your handling code here:
        System.out.println("enrtramos");
        switch (jComboBox_ejemplos.getSelectedIndex()) {
            case 0:
                jLabel_res.setText("---");
                System.out.println("en cero");
                expReg = "#([a-fA-F]|[0-9]){3,6}";
                jTextField_regex.setText(expReg);
                cad = "#ffffff";
                jTextField_cadena.setText(cad);
                jButton_cambiar.doClick();
                break;
            case 1:
                jLabel_res.setText("---");
                System.out.println("en uno");
                expReg = "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,63}";
                jTextField_regex.setText(expReg);
                cad = "ejemplo@correo.com";
                jTextField_cadena.setText(cad);
                jButton_cambiar.doClick();
                break;
            case 2:
                jLabel_res.setText("---");
                System.out.println("en dos");
                expReg = "\\d{1,3}(?=(\\d{3})+(?!\\d))";
                jTextField_regex.setText(expReg);
                cad = "1000";
                jTextField_cadena.setText(cad);
                jButton_cambiar.doClick();
                break;
            case 3:
                jLabel_res.setText("---");
                System.out.println("en cuatro");
                expReg = "(?:https?://)?(?:www\\.)?youtube\\.com/watch\\?v=\\w{11}";
                jTextField_regex.setText(expReg);
                cad = "https://www.youtube.com/watch?v=dQw4w9WgXcQ";
                jTextField_cadena.setText(cad);
                jButton_cambiar.doClick();
                break;
            case 4:
                jLabel_res.setText("---");
                System.out.println("en cinco");
                expReg = "\\b(?=(?:\\D*\\d){10}(?:\\D*\\d|\\b))(?:\\d[-]?){3}\\d\\b|\\b(?=(?:\\D*\\d){13}\\D*\\b)[\\d-]+\\b";
                jTextField_regex.setText(expReg);
                cad = "978-0-306-40615-7";
                jTextField_cadena.setText(cad);
                jButton_cambiar.doClick();
                break;
            case 5:
                jLabel_res.setText("---");
                System.out.println("en seis");
                expReg = "@([A-Za-z0-9_]{1,15})";
                jTextField_regex.setText(expReg);
                cad = "@lilmonix3";
                jTextField_cadena.setText(cad);
                jButton_cambiar.doClick();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jComboBox_ejemplosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cambiar;
    private javax.swing.JButton jButton_comprobar;
    private javax.swing.JComboBox<String> jComboBox_ejemplos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_regex;
    private javax.swing.JLabel jLabel_res;
    private javax.swing.JTextField jTextField_cadena;
    private javax.swing.JTextField jTextField_regex;
    // End of variables declaration//GEN-END:variables
}
